<?php
add_action( 'init', function() {
	register_taxonomy( 'project-category', array(
	0 => 'projects',
), array(
	'labels' => array(
		'name' => 'Project Categories',
		'singular_name' => 'Project Category',
		'menu_name' => 'Project Categories',
		'all_items' => 'All Project Categories',
		'edit_item' => 'Edit Project Category',
		'view_item' => 'View Project Category',
		'update_item' => 'Update Project Category',
		'add_new_item' => 'Add New Project Category',
		'new_item_name' => 'New Project Category Name',
		'parent_item' => 'Parent Project Category',
		'parent_item_colon' => 'Parent Project Category:',
		'search_items' => 'Search Project Categories',
		'not_found' => 'No project categories found',
		'no_terms' => 'No project categories',
		'filter_by_item' => 'Filter by project category',
		'items_list_navigation' => 'Project Categories list navigation',
		'items_list' => 'Project Categories list',
		'back_to_items' => '← Go to project categories',
		'item_link' => 'Project Category Link',
		'item_link_description' => 'A link to a project category',
	),
	'public' => true,
	'hierarchical' => true,
	'show_in_menu' => true,
	'show_in_rest' => true,
	'show_tagcloud' => false,
	'show_admin_column' => true,
	'sort' => true,
) );

	register_taxonomy( 'project-tag', array(
	0 => 'projects',
), array(
	'labels' => array(
		'name' => 'Project Tags',
		'singular_name' => 'Project Tag',
		'menu_name' => 'Project Tags',
		'all_items' => 'All Project Tags',
		'edit_item' => 'Edit Project Tag',
		'view_item' => 'View Project Tag',
		'update_item' => 'Update Project Tag',
		'add_new_item' => 'Add New Project Tag',
		'new_item_name' => 'New Project Tag Name',
		'search_items' => 'Search Project Tags',
		'popular_items' => 'Popular Project Tags',
		'separate_items_with_commas' => 'Separate project tags with commas',
		'add_or_remove_items' => 'Add or remove project tags',
		'choose_from_most_used' => 'Choose from the most used project tags',
		'not_found' => 'No project tags found',
		'no_terms' => 'No project tags',
		'items_list_navigation' => 'Project Tags list navigation',
		'items_list' => 'Project Tags list',
		'back_to_items' => '← Go to project tags',
		'item_link' => 'Project Tag Link',
		'item_link_description' => 'A link to a project tag',
	),
	'public' => true,
	'show_in_menu' => true,
	'show_in_rest' => true,
	'show_admin_column' => true,
	'sort' => true,
) );
} );

add_action( 'init', function() {
	register_post_type( 'education', array(
	'labels' => array(
		'name' => 'Educations',
		'singular_name' => 'Education',
		'menu_name' => 'Educations',
		'all_items' => 'All Educations',
		'edit_item' => 'Edit Education',
		'view_item' => 'View Education',
		'view_items' => 'View Educations',
		'add_new_item' => 'Add New Education',
		'add_new' => 'Add New Education',
		'new_item' => 'New Education',
		'parent_item_colon' => 'Parent Education:',
		'search_items' => 'Search Educations',
		'not_found' => 'No educations found',
		'not_found_in_trash' => 'No educations found in Trash',
		'archives' => 'Education Archives',
		'attributes' => 'Education Attributes',
		'insert_into_item' => 'Insert into education',
		'uploaded_to_this_item' => 'Uploaded to this education',
		'filter_items_list' => 'Filter educations list',
		'filter_by_date' => 'Filter educations by date',
		'items_list_navigation' => 'Educations list navigation',
		'items_list' => 'Educations list',
		'item_published' => 'Education published.',
		'item_published_privately' => 'Education published privately.',
		'item_reverted_to_draft' => 'Education reverted to draft.',
		'item_scheduled' => 'Education scheduled.',
		'item_updated' => 'Education updated.',
		'item_link' => 'Education Link',
		'item_link_description' => 'A link to a education.',
	),
	'public' => true,
	'hierarchical' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-welcome-learn-more',
	'supports' => array(
		0 => 'title',
		1 => 'editor',
	),
	'delete_with_user' => false,
) );

	register_post_type( 'experience', array(
	'labels' => array(
		'name' => 'Experiences',
		'singular_name' => 'Experience',
		'menu_name' => 'Experience',
		'all_items' => 'All experience',
		'edit_item' => 'Edit experience',
		'view_item' => 'View experience',
		'view_items' => 'View experience',
		'add_new_item' => 'Add New experience',
		'add_new' => 'Add New experience',
		'new_item' => 'New experience',
		'parent_item_colon' => 'Parent experience:',
		'search_items' => 'Search experience',
		'not_found' => 'No experience found',
		'not_found_in_trash' => 'No experience found in Trash',
		'archives' => 'experience Archives',
		'attributes' => 'experience Attributes',
		'insert_into_item' => 'Insert into experience',
		'uploaded_to_this_item' => 'Uploaded to this experience',
		'filter_items_list' => 'Filter experience list',
		'filter_by_date' => 'Filter experience by date',
		'items_list_navigation' => 'experience list navigation',
		'items_list' => 'exprean list',
		'item_published' => 'experience published.',
		'item_published_privately' => 'experience published privately.',
		'item_reverted_to_draft' => 'experience reverted to draft.',
		'item_scheduled' => 'experience scheduled.',
		'item_updated' => 'experience updated.',
		'item_link' => 'experience Link',
		'item_link_description' => 'A link to a experience.',
	),
	'public' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-buddicons-buddypress-logo',
	'supports' => array(
		0 => 'title',
		1 => 'editor',
	),
	'delete_with_user' => false,
) );

	register_post_type( 'projects', array(
	'labels' => array(
		'name' => 'Projects',
		'singular_name' => 'Projects',
		'menu_name' => 'Projects',
		'all_items' => 'All Projects',
		'edit_item' => 'Edit Projects',
		'view_item' => 'View Projects',
		'view_items' => 'View Projects',
		'add_new_item' => 'Add New Projects',
		'add_new' => 'Add New Projects',
		'new_item' => 'New Projects',
		'parent_item_colon' => 'Parent Projects:',
		'search_items' => 'Search Projects',
		'not_found' => 'No projects found',
		'not_found_in_trash' => 'No projects found in Trash',
		'archives' => 'Projects Archives',
		'attributes' => 'Projects Attributes',
		'featured_image' => 'Project Feature',
		'set_featured_image' => 'Set Project Feature',
		'remove_featured_image' => 'Remove Project Feature',
		'use_featured_image' => 'Use Project Feature',
		'insert_into_item' => 'Insert into projects',
		'uploaded_to_this_item' => 'Uploaded to this projects',
		'filter_items_list' => 'Filter projects list',
		'filter_by_date' => 'Filter projects by date',
		'items_list_navigation' => 'Projects list navigation',
		'items_list' => 'Projects list',
		'item_published' => 'Projects published.',
		'item_published_privately' => 'Projects published privately.',
		'item_reverted_to_draft' => 'Projects reverted to draft.',
		'item_scheduled' => 'Projects scheduled.',
		'item_updated' => 'Projects updated.',
		'item_link' => 'Projects Link',
		'item_link_description' => 'A link to a projects.',
	),
	'description' => 'Could you clarify what you mean by "Generate Company DesVert"? Are you looking for a short description for a company named "DesVert," or is there something else you\'d like help with? Also, do you have specific projects in mind for the post type description?',
	'public' => true,
	'hierarchical' => true,
	'exclude_from_search' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-schedule',
	'supports' => array(
		0 => 'title',
		1 => 'editor',
		2 => 'thumbnail',
	),
	'delete_with_user' => false,
) );

	register_post_type( 'service', array(
	'labels' => array(
		'name' => 'Services',
		'singular_name' => 'Service',
		'menu_name' => 'Services',
		'all_items' => 'All Services',
		'edit_item' => 'Edit Service',
		'view_item' => 'View Service',
		'view_items' => 'View Services',
		'add_new_item' => 'Add New Service',
		'add_new' => 'Add New Service',
		'new_item' => 'New Service',
		'parent_item_colon' => 'Parent Service:',
		'search_items' => 'Search Services',
		'not_found' => 'No services found',
		'not_found_in_trash' => 'No services found in Trash',
		'archives' => 'Service Archives',
		'attributes' => 'Service Attributes',
		'insert_into_item' => 'Insert into service',
		'uploaded_to_this_item' => 'Uploaded to this service',
		'filter_items_list' => 'Filter services list',
		'filter_by_date' => 'Filter services by date',
		'items_list_navigation' => 'Services list navigation',
		'items_list' => 'Services list',
		'item_published' => 'Service published.',
		'item_published_privately' => 'Service published privately.',
		'item_reverted_to_draft' => 'Service reverted to draft.',
		'item_scheduled' => 'Service scheduled.',
		'item_updated' => 'Service updated.',
		'item_link' => 'Service Link',
		'item_link_description' => 'A link to a service.',
	),
	'public' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-admin-generic',
	'supports' => array(
		0 => 'title',
		1 => 'editor',
	),
	'delete_with_user' => false,
) );
} );


add_filter( 'enter_title_here', function( $default, $post ) {
	switch ( $post->post_type ) {
		case 'education':
			return 'Name of Degree';
		case 'experience':
			return 'Job Position';
		case 'projects':
			return 'Project Title';
		case 'service':
			return 'Services Title';
	}

	return $default;
}, 10, 2 );

